Repository CMU-313/fall23-nodebb-poncho, pull requests merged in 2023-10, with the labels that each got.

#30 fixed build bug with @black css
  themes/nodebb-theme-persona/less/account.less
Labels: bug

#34 Anonymous feature drop down
  .gitignore
  node_modules/nodebb-plugin-composer-default/.eslintrc
  node_modules/nodebb-plugin-composer-default/.gitattributes
  node_modules/nodebb-plugin-composer-default/.jshintrc
  node_modules/nodebb-plugin-composer-default/LICENSE
  node_modules/nodebb-plugin-composer-default/README.md
  node_modules/nodebb-plugin-composer-default/controllers.js
  node_modules/nodebb-plugin-composer-default/library.js
  node_modules/nodebb-plugin-composer-default/package.json
  node_modules/nodebb-plugin-composer-default/plugin.json
  node_modules/nodebb-plugin-composer-default/screenshots/desktop.png
  node_modules/nodebb-plugin-composer-default/screenshots/mobile.png
  node_modules/nodebb-plugin-composer-default/static/less/composer.less
  node_modules/nodebb-plugin-composer-default/static/less/medium.less
  node_modules/nodebb-plugin-composer-default/static/less/page-compose.less
  node_modules/nodebb-plugin-composer-default/static/less/textcomplete.less
  node_modules/nodebb-plugin-composer-default/static/less/zen-mode.less
  node_modules/nodebb-plugin-composer-default/static/lib/.eslintrc
  node_modules/nodebb-plugin-composer-default/static/lib/admin.js
  node_modules/nodebb-plugin-composer-default/static/lib/client.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/autocomplete.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/categoryList.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/controls.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/drafts.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/formatting.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/preview.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/resize.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/scheduler.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/tags.js
  node_modules/nodebb-plugin-composer-default/static/lib/composer/uploads.js
  node_modules/nodebb-plugin-composer-default/static/templates/admin/plugins/composer-default.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/compose.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/composer.tpl
  node_modules/nodebb-plugin-composer-default/static/templates/modals/topic-scheduler.tpl
  node_modules/nodebb-plugin-composer-default/websockets.js
  themes/nodebb-theme-persona/templates/partials/buttons/newTopic.tpl
Labels: enhancement, student view, instructor view, testing

#33 fixed tester -- should pass test unless async timeout errors
  public/openapi/components/schemas/TopicObject.yaml
  src/topics/data.js
  test/api.js
Labels: bug, testing
